apiVersion: apps/v1
kind: Deployment
metadata: 
  name: quote-collector
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: quoteCollector
  template: 
    metadata:
      labels:
        app: quoteCollector
    spec:
      containers: 
      - name: frontend
        image: tishathakral/quote-collector:1405af31b5d996c68915301db330abd34e8a41e9
        ports: 
        - containerPort: 3000

