apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quote-collector-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/x-forward-proto: "https"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - test.narottamchy.in
      secretName: my-tls-secret
  rules:
    - host: test.narottamchy.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quote-collector-service
                port:
                  number: 3000