apiVersion: v1
kind: Service
metadata: 
  name: quote-collector-service
spec: 
  selector:
    app: quoteCollector
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP