apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quote-collector-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - test.narottamchy.in
      secretName: quote-collector-prod-secret
  rules:
    - host: test.narottamchy.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quote-collector-service
                port:
                  number: 80